name: 上游自动同步并编译

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0:00 自动检查一次更新
  workflow_dispatch:      # 允许你手动点击按钮同步

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用默认 token
          fetch-depth: 0

      - name: 同步上游代码
        uses: a260020290/pull-request-mirror-action@v1.1.0 # 这是一个常用的同步工具
        with:
          base: master         # 你的分支（如果是 main 请改写）
          head: master         # 上游的分支（通常是 master 或 dev）
          owner: fulishare     # 上游作者名
          repo: tdesktop-x64   # 上游仓库名

  # 同步完成后，由于代码发生了 push，你的 win.yml 只要设置了 on: push 就会自动开始编译
